### ISSUE TITLE
NATS Streaming

### ISSUE THREAD

**Issue by dairlair** [dairlair/tweetwatch#45]
As a DevOps, I want to have an option to stream all received tweets to NATS Streaming Server that let me build an event-driven cluster with further tweets processing.

How should it works:

The application config has this section

```yaml
nats:
    url: ""
    clusterId: ""
    clientId: ""
```

If NATS configured then each saved tweet should be sent to the NATS Streaming server.
